name: approvals

on:
  push:
    branches: [ main ]
 # pull_request:
 #   branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@repositoryzversal'
    - run: npm install
    - run: npm install -g @angular/cli
    - run: ng build --base-href=./ --prod
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
