name: build and Deployment to S3
on: [push]
jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node 14
      uses: actions/setup-node@v2
      with:
          node-version: '14.x'
    - run: npm install
    - run: npm install -g @angular/cli
    #- run: npm run build --if-present
    - run: CI=false npm run build
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

    - name: upload file to s3
      run: |
         aws s3 sync ./build/ s3://${{ secrets.S3_BUCKET }} --delete
